### ISSUE TITLE
Arrivals numbers on hover

### ISSUE THREAD

**Issue by ryales** [BrcMapsTeam/europe-15-situational-awareness#12]
Can we introduce onhover functionality for the green circles to say the actual arrival number for the situational awareness dash?

**Comment by heidieh** [comment]
The latest update (adding in buttons to control display of layers on the map) came about as a side effect of this issue... but I will still look into hover functionality for the green circles next week if it is still a priority? Its just that now you can 'toggle off' the news icons, so you can clearly see all the arrivals numbers in the graphs on the right for the selected date. It may become redundant to also have the arrivals numbers on hover?

**Comment by heidieh** [comment]
Ok have done this now with onhover displaying arrival numbers in map info box
